- name: Setup Fedora Workstation
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Configure system hostname
      ansible.builtin.hostname:
        name: "touchbar"
    - name: Import shared tasks
      ansible.builtin.import_tasks:
        file: playbook-shared.yml
    - name: Additional workstate packages
      ansible.builtin.dnf:
        name:
          - alacritty
          - btop
          - conky
          - grimshot
          - pass
          - python3-pip
          - python3-i3ipc
          - sway
          - sway-systemd
          - waybar
        state: present
    - name: Install autotiling via pip for user
      ansible.builtin.pip:
        name: autotiling
        extra_args: --user
        state: present
      become_user: jylitalo
    - name: Add Flathub
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    - name: Install Logseq
      community.general.flatpak:
        name: com.logseq.Logseq
        state: present
        remote: flathub
